const translations = {
    es: {
        download_pdf: "Descargar PDF",
        lang_fr: "Français (Francés)",
        lang_de: "Deutsch (Alemán)",
        lang_it: "Italiano (Italiano)",
        lang_pt: "Português (Portugués)",
        lang_ja: "日本語 (Japonés)",
        lang_zh: "中文 (Chino)",
        lang_hi: "हिन्दी (Hindi)",
        lang_ar: "العربية (Árabe)",
        lang_ru: "Русский (Ruso)",
        lang_ko: "한국어 (Coreano)",
        name: "Ricardo Alexander Rivas Martínez",
        phone: "+503 7099-1184",
        email: "rivasricardo90@gmail.com",
        location: "El Salvador",
        linkedin: "LinkedIn: Ricardo Rivas",
        github: "GitHub: RDICHARD872",
        profile_heading: "Perfil Profesional",
        profile_desc: "Estudiante de Ingeniería en Ciencias de la Computación y apasionado por la tecnología, con experiencia sólida en soporte técnico, infraestructura de redes y plataformas de realidad virtual. Profesionalmente adaptable, con una fuerte capacidad para asimilar rápidamente nuevos lenguajes de programación y tecnologías emergentes sin limitarse a un solo entorno. Experiencia práctica en despliegues corporativos y académicos, combinando habilidades en hardware, administración de servidores y automatización.",
        exp_heading: "Experiencia Laboral",
        job1_title: "Técnico en Realidad Virtual e Infraestructura de Redes",
        job1_company: "Corporación Digital | El Salvador (2023 - Presente)",
        job1_desc: "Gestión, instalación y soporte técnico de entornos de realidad virtual basados en la plataforma Viroo para despliegues en sedes universitarias. Instalación y mantenimiento de infraestructura física de redes, abarcando terminación de conexiones (ponchado de cables) y organización de cableado estructurado en racks de comunicaciones.",
        job2_title: "Capacitación en Automatización",
        job2_company: "Microsense | Alemania (2025)",
        edu_heading: "Educación",
        edu1_degree: "Ingeniería en Ciencias de la Computación (2023 - 2027, Fecha esperada de graduación)",
        edu1_school: "Universidad Francisco Gavidia | El Salvador",
        edu2_degree: "Bachillerato Técnico Vocacional en Electromecánica (EMCA) (2015-2020)",
        edu2_school: "Instituto Técnico Ricaldone | San Salvador",
        edu2_desc: "Programa técnico especial de 3 años.",
        edu3_degree: "Estudios de Paramédico (2.5 años de formación)",
        edu3_school: "Formación Médica",
        edu4_degree: "Estudios de Inglés (2016 - 2020)",
        edu4_school: "Centro Cultural Salvadoreño Americano",
        skills_heading: "Habilidades Técnicas",
        skill1_name: "Programación",
        skill1_desc: "Conocimientos en C++, C# y JavaScript, destacando una alta capacidad de aprendizaje autodidacta para adoptar nuevos lenguajes según las necesidades del proyecto.",
        skill2_name: "Infraestructura y Redes",
        skill2_desc: "Administración de servidores (Linux/Windows), enrutamiento, túneles VPN, accesos remotos (SSH) y monitoreo de sistemas (Zabbix).",
        skill3_name: "Hardware y Tecnologías Emergentes",
        skill3_desc: "Configuración de hardware de alto rendimiento y flujos de trabajo de IA local.",
        lang_heading: "Idiomas",
        lang1_name: "Español",
        lang1_level: "Nativo",
        lang2_name: "Inglés",
        lang2_level: "Fluido / Avanzado",
        hobbies_heading: "Pasatiempos e Intereses",
        hobbies_desc: "Amante de la tecnología con un enfoque práctico en la optimización de sistemas para ahorrar tiempo, dinero y esfuerzos. Este interés lo aplico de manera activa en la domótica de mi habitación, utilizando Home Assistant para gestionar dispositivos y crear rutinas eficientes de automatización.",
        ref_heading: "Referencias",
        ref_personal_heading: "Referencias Personales",
        ref_p1_name: "Iliana Orellana",
        ref_p1_relation: "(Amiga)",
        ref_p1_phone: "Teléfono: +503 7027 7978",
        ref_p1_email: "Correo: gabrielaorellana1000@gmail.com",
        ref_p2_name: "Carlos Herrera",
        ref_p2_relation: "(Amigo)",
        ref_p2_phone: "Teléfono: +1 (239) 326-7625",
        ref_p2_email: "Correo: carlosherreramtnz@gmail.com",
        ref_p3_name: "Julio Murcia",
        ref_p3_relation: "(Amigo)",
        ref_p3_phone: "Teléfono: +1 (857) 230-6985",
        ref_p3_email: "Correo: jrmmdz7@gmail.com",
        ref_family_heading: "Referencias Familiares",
        ref_f1_name: "Alexander Rivas",
        ref_f1_relation: "(Padre)",
        ref_f1_phone: "Teléfono: +503 7988 3233",
        ref_f1_email: "Correo: rivas.alexander@gmail.com",
        ref_f2_name: "Guillermo Rivas",
        ref_f2_relation: "(Tío)",
        ref_f2_phone: "Teléfono: +1 (720) 688-6505",
        ref_f2_email: "Correo: guillermoantoniorivas@gmail.com",
        ref_f3_name: "Wendy Rivas",
        ref_f3_relation: "(Tía)",
        ref_f3_phone: "Teléfono: +503 7741 2949",
        ref_f3_email: ""
    },
    en: {
        download_pdf: "Download PDF",
        lang_fr: "Français (French)",
        lang_de: "Deutsch (German)",
        lang_it: "Italiano (Italian)",
        lang_pt: "Português (Portuguese)",
        lang_ja: "日本語 (Japanese)",
        lang_zh: "中文 (Chinese)",
        lang_hi: "हिन्दी (Hindi)",
        lang_ar: "العربية (Arabic)",
        lang_ru: "Русский (Russian)",
        lang_ko: "한국어 (Korean)",
        name: "Ricardo Alexander Rivas Martínez",
        phone: "+503 7099-1184",
        email: "rivasricardo90@gmail.com",
        location: "El Salvador",
        linkedin: "LinkedIn: Ricardo Rivas",
        github: "GitHub: RDICHARD872",
        profile_heading: "Professional Profile",
        profile_desc: "Computer Science Engineering student and technology enthusiast with solid experience in technical support, network infrastructure, and virtual reality platforms. Professionally adaptable, with a strong ability to quickly assimilate new programming languages and emerging technologies without being limited to a single environment. Practical experience in corporate and academic deployments, combining hardware, server administration, and automation skills.",
        exp_heading: "Work Experience",
        job1_title: "Virtual Reality and Network Infrastructure Technician",
        job1_company: "Corporación Digital | El Salvador (2023 - Present)",
        job1_desc: "Management, installation, and technical support of virtual reality environments based on the Viroo platform for deployments in university campuses. Installation and maintenance of physical network infrastructure, including connection termination (cable crimping) and structured cabling organization in communication racks.",
        job2_title: "Automation Training",
        job2_company: "Microsense | Germany (2025)",
        edu_heading: "Education",
        edu1_degree: "B.S. in Computer Science Engineering (2023 - 2027, Expected Graduation)",
        edu1_school: "Universidad Francisco Gavidia | El Salvador",
        edu2_degree: "Vocational Technical High School Diploma in Electromechanics (EMCA) (2015-2020)",
        edu2_school: "Instituto Técnico Ricaldone | San Salvador",
        edu2_desc: "Special 3-year technical program.",
        edu3_degree: "Paramedic Studies (2.5 years of training)",
        edu3_school: "Medical Training",
        edu4_degree: "English Studies (2016 - 2020)",
        edu4_school: "Centro Cultural Salvadoreño Americano",
        skills_heading: "Technical Skills",
        skill1_name: "Programming",
        skill1_desc: "Knowledge of C++, C#, and JavaScript, highlighting a high capacity for self-taught learning to adopt new languages according to project needs.",
        skill2_name: "Infrastructure and Networks",
        skill2_desc: "Server administration (Linux/Windows), routing, VPN tunnels, remote access (SSH), and system monitoring (Zabbix).",
        skill3_name: "Hardware and Emerging Technologies",
        skill3_desc: "High-performance hardware configuration and local AI workflows.",
        lang_heading: "Languages",
        lang1_name: "Spanish",
        lang1_level: "Native",
        lang2_name: "English",
        lang2_level: "Fluent / Advanced",
        hobbies_heading: "Hobbies and Interests",
        hobbies_desc: "Technology lover with a practical approach to optimizing systems to save time, money, and effort. I actively apply this interest to my room's home automation, using Home Assistant to manage devices and create efficient automation routines.",
        ref_heading: "References",
        ref_personal_heading: "Personal References",
        ref_p1_name: "Iliana Orellana",
        ref_p1_relation: "(Friend)",
        ref_p1_phone: "Phone: +503 7027 7978",
        ref_p1_email: "Email: gabrielaorellana1000@gmail.com",
        ref_p2_name: "Carlos Herrera",
        ref_p2_relation: "(Friend)",
        ref_p2_phone: "Phone: +1 (239) 326-7625",
        ref_p2_email: "Email: carlosherreramtnz@gmail.com",
        ref_p3_name: "Julio Murcia",
        ref_p3_relation: "(Friend)",
        ref_p3_phone: "Phone: +1 (857) 230-6985",
        ref_p3_email: "Email: jrmmdz7@gmail.com",
        ref_family_heading: "Family References",
        ref_f1_name: "Alexander Rivas",
        ref_f1_relation: "(Father)",
        ref_f1_phone: "Phone: +503 7988 3233",
        ref_f1_email: "Email: rivas.alexander@gmail.com",
        ref_f2_name: "Guillermo Rivas",
        ref_f2_relation: "(Uncle)",
        ref_f2_phone: "Phone: +1 (720) 688-6505",
        ref_f2_email: "Email: guillermoantoniorivas@gmail.com",
        ref_f3_name: "Wendy Rivas",
        ref_f3_relation: "(Aunt)",
        ref_f3_phone: "Phone: +503 7741 2949",
        ref_f3_email: ""
    }
};